services:
  backend:
    image: ${DOCKER_HUB_USER:-yerriiniii}/inventory-backend:latest
    container_name: inventory-backend
    restart: always
    pull_policy: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: ${DOCKER_HUB_USER:-yerriiniii}/inventory-frontend:latest
    container_name: inventory-frontend
    restart: always
    pull_policy: always
    ports:
      - "80:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"