services:
  backend:
    image: ${DOCKER_HUB_USER:-yerriiniii}/adaptscm-backend:latest
    container_name: adaptscm-backend
    restart: always
    pull_policy: always
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    image: ${DOCKER_HUB_USER:-yerriiniii}/adaptscm-frontend:latest
    container_name: adaptscm-frontend
    restart: always
    pull_policy: always
    ports:
      - "3000:80"
