name: Deploy to EC2

# force rerun

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            echo "🚀 Deploy start"

            cd ~/Inventory-System || exit 1

            echo "📦 Git pull"
            git pull origin develop

            echo "🧱 Frontend build"
            cd frontend || exit 1
            npm install
            npm run build

            echo "🗑️ Clean old static files"
            sudo rm -rf /var/www/inventory/*

            echo "📁 Copy new static files"
            sudo cp -r dist/* /var/www/inventory/

            echo "🔁 Restart backend"
            cd ..
            sudo systemctl restart inventory-api

            echo "♻️ Reload nginx"
            sudo systemctl reload nginx

            echo "✅ Deploy complete"